# Generated by Django 6.0.5 on 2026-05-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveThought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(help_text="tell me what ya thinkin' yonkbot", max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(help_text='Short headline summary of the solution.', max_length=300)),
                ('role', models.CharField(default='Product Manager & UX Designer', max_length=100)),
                ('timeline', models.CharField(help_text='e.g., Q3 2025', max_length=50)),
                ('impact_metric', models.CharField(help_text='e.g., +40% Conversion', max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Lower numbers display first.')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
